apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gj99lzeyt-python
  janus-idp.io/tekton: gj99lzeyt-python
  backstage.io/kubernetes-id: gj99lzeyt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gj99lzeyt-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
