apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: gj99lzeyt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gj99lzeyt-python 
  name: gj99lzeyt-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gj99lzeyt-python
    weight: 100 
