apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gj99lzeyt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gj99lzeyt-python 
  name: gj99lzeyt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gj99lzeyt-python 
